dbt_project:
  outputs:
    dev:
      type: duckdb
      path: reports/sources/final/dev.duckdb
      threads: 2

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4

  target: dev
